apiVersion: v1
kind: ResourceQuota
metadata:
  name: fintrack-quota
  namespace: fintrack
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "2Gi"
    limits.cpu: "4"
    limits.memory: "3Gi"
    pods: "20"
