apiVersion: v1
kind: ResourceQuota
metadata:
  name: fintrack-quota
  namespace: fintrack
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "1"
    limits.memory: "768Mi"
    pods: "10"
